# Generated by Django 6.1.1 on 2026-09-29 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.UUIDField(help_text='Not a foreign key: a deleted lesson must still leave the index.')),
                ('reason', models.CharField(choices=[('published', 'Content published'), ('reconcile', 'Found out of step by sync_ai_index'), ('manual', 'Requested in the admin')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('generation', models.PositiveIntegerField(default=0, help_text='Bumped when the lesson changes again while pending.')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(blank=True, choices=[('index', 'Index'), ('delete', 'Delete')], help_text='What was last sent.', max_length=10)),
                ('target_version_id', models.UUIDField(blank=True, help_text='The content version last sent.', null=True)),
                ('retryable', models.BooleanField(default=True, help_text='False when the AI service refused the request itself.')),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='aiservice_ir_due_idx'), models.Index(fields=['lesson_id'], name='aiservice_ir_lesson_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('lesson_id',), name='one_pending_index_request_per_lesson')],
            },
        ),
    ]
