# Generated by Django 6.1.1 on 2026-09-28 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('version', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('effective_from', models.DateField()),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('notify_by', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'SMS and email')], default='both', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=150)),
                ('short_bio', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_contact', models.CharField(max_length=254)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=5)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('reported', 'Reported (not my child)')], default='sent', max_length=10)),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=10)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('given_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.consenttext')),
                ('guardian_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='accounts.guardianlink')),
            ],
            options={
                'ordering': ['-given_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('batch_teacher', 'Batch teacher'), ('curriculum_lead', 'Curriculum lead'), ('operations', 'Operations'), ('super_admin', 'Super admin')], max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=80)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('awaiting_consent', 'Awaiting parent approval'), ('active', 'Active'), ('paused', 'Paused (consent withdrawn)'), ('deleted', 'Deleted')], default='awaiting_consent', max_length=20)),
                ('awaiting_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.board')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=254)),
                ('purpose', models.CharField(choices=[('verify_contact', 'Verify contact'), ('login', 'Log in'), ('reset_password', 'Reset password')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'purpose', 'created_at'], name='accounts_ve_destina_140051_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('is_primary', True)), fields=('student',), name='one_active_primary_guardian'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('parent', 'student'), name='one_active_link_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role', 'subject', 'class_level'), name='one_active_grant_per_scope', nulls_distinct=False),
        ),
    ]
