# Generated by Django 6.1.1 on 2026-09-29 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_course_module_lesson_course_free_module_programme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_version_id', models.UUIDField(help_text='The published lesson version when the chat started.')),
                ('mode', models.CharField(choices=[('explain', 'Explain'), ('socratic', 'Guide me'), ('hint', 'Hint')], default='explain', max_length=10)),
                ('pinned_chunk_ids', models.JSONField(blank=True, default=list, help_text='Lesson passages chosen by the AI service.')),
                ('flagged', models.BooleanField(default=False, help_text='At least one safety flag was raised in this chat.')),
                ('hidden_by_student', models.BooleanField(default=False, help_text='Deleted by the student but kept for a flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('text', models.TextField()),
                ('mode', models.CharField(choices=[('explain', 'Explain'), ('socratic', 'Guide me'), ('hint', 'Hint')], default='explain', max_length=10)),
                ('blocked', models.BooleanField(default=False, help_text='Answered with a fixed safety reply.')),
                ('replaced', models.BooleanField(default=False, help_text="The model's reply was stopped and replaced.")),
                ('off_topic', models.BooleanField(default=False)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('safety_version', models.CharField(blank=True, max_length=40)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('reply_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.tutorconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SafetyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='input (student) or output (tutor)', max_length=10)),
                ('category', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('parent_visible', models.BooleanField(default=False, help_text='High and critical: the parent sees the chat (D13).')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tutor.tutorconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tutor.tutormessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='IST day (C14).')),
                ('messages', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tutorconversation',
            index=models.Index(fields=['student', 'lesson', '-last_message_at'], name='tutor_conv_student_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorconversation',
            index=models.Index(fields=['last_message_at'], name='tutor_conv_retention_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyflag',
            index=models.Index(fields=['status', 'severity'], name='tutor_flag_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('student', 'day'), name='unique_tutor_usage_per_day'),
        ),
    ]
