# Generated by Django 6.1.1 on 2026-09-28 20:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('track', models.CharField(choices=[('foundation', 'Foundation'), ('ai_in_subject', 'AI in the subject'), ('frontier_ai', 'Frontier AI')], default='foundation', max_length=20)),
                ('path_stage', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_paise', models.PositiveIntegerField(default=0, help_text='Whole paise: ₹499 = 49900.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, help_text='Empty for board-independent courses such as AI Foundations.', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalogue.subject')),
            ],
            options={
                'ordering': ['subject__order', 'class_level__number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalogue.course')),
            ],
            options={
                'ordering': ['course', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('est_minutes', models.PositiveSmallIntegerField(default=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalogue.module')),
            ],
            options={
                'ordering': ['module__course', 'module__position', 'position'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='free_module',
            field=models.ForeignKey(blank=True, help_text='Readable without buying (decision Q5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.module'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('path_stage', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_paise', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
            ],
            options={
                'ordering': ['path_stage', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme_links', to='catalogue.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='catalogue.programme')),
            ],
            options={
                'ordering': ['programme', 'position'],
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='courses',
            field=models.ManyToManyField(related_name='programmes', through='catalogue.ProgrammeCourse', to='catalogue.course'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable forever, e.g. MATH-FRAC-ADD.', max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='catalogue.subject')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LessonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teaches', 'Teaches'), ('revises', 'Revises')], default='teaches', max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='catalogue.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_links', to='catalogue.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', through='catalogue.SkillPrerequisite', to='catalogue.skill'),
        ),
        migrations.CreateModel(
            name='BoardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_ref', models.CharField(help_text="e.g. 'Chapter 3: Linear equations'", max_length=120)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.board')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.classlevel')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_mappings', to='catalogue.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'board', 'class_level'), name='unique_board_mapping')],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_module_position'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='unique_lesson_position'),
        ),
        migrations.AddConstraint(
            model_name='programmecourse',
            constraint=models.UniqueConstraint(fields=('programme', 'course'), name='unique_programme_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonskill',
            constraint=models.UniqueConstraint(fields=('lesson', 'skill'), name='unique_lesson_skill'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.UniqueConstraint(fields=('skill', 'requires'), name='unique_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('skill', models.F('requires')), _negated=True), name='no_self_prerequisite'),
        ),
    ]
