# Generated by Django 6.1.1 on 2026-09-28 20:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_course_module_lesson_course_free_module_programme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('lesson_quiz', 'Lesson quiz'), ('warmup', 'Warm-up check')], default='lesson_quiz', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessment.attempt')),
            ],
            options={
                'ordering': ['attempt', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(null=True)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('marked_by', models.CharField(choices=[('code', 'Code'), ('ai', 'AI'), ('teacher', 'Teacher')], default='code', max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessment.attemptitem')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mcq', 'Multiple choice'), ('short_answer', 'Short answer (AI-marked, later)')], default='mcq', max_length=15)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('purpose', models.CharField(choices=[('quiz', 'Lesson quiz'), ('practice', 'Practice'), ('warmup', 'Warm-up check'), ('exploratory', 'Exploratory test')], default='quiz', max_length=12)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalogue.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalogue.skill')),
            ],
            options={
                'ordering': ['lesson', 'position'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('body', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_ai_draft', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessment.question')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessment.questionversion'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_no'), name='unique_question_version_no'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('question',), name='one_published_version_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('reviewer__isnull', True), models.Q(('reviewer', models.F('author')), _negated=True), _connector='OR'), name='question_reviewer_is_not_author'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_item_position'),
        ),
    ]
